import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/sidebar/sidebar";


import { Poppins } from 'next/font/google';
import Header from "@/components/header";
import { IMAGES } from "@/constants/image";

const fontPoppins = Poppins({
  weight: '500',
  subsets: ['latin'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fontPoppins.variable}, ${fontPoppins.className}`}>
      <body
        className={`${fontPoppins.variable} antialiased p-4`}
      >
        <Sidebar />
        <div className="pl-[320px] mx-4  bg-white w-full h-full ">
          <Header user={{ name: "Jack Jonson", role: "Admin", avatarUrl: IMAGES.avatar }} />
          {children}
        </div>

      </body>
    </html>
  );
}
